/*
  Auto-generated by Spline
*/

"use client"


import useSpline from '@splinetool/r3f-spline'
import { PerspectiveCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/dMi9u-m0LTMYpwyS/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#74757a']} />
      <group {...props} dispose={null}>
        <mesh
          name="Rectangle"
          geometry={nodes.Rectangle.geometry}
          material={materials['Rectangle Material']}
          castShadow
          receiveShadow
          position={[34.57, 15.27, 22.98]}
          rotation={[0.04, -0.25, -0.04]}
          scale={[1, 1, 1.14]}
        />
        <PerspectiveCamera
          name="Camera"
          makeDefault={true}
          far={100000}
          near={70}
          fov={17}
          position={[-120.75, 159.51, 290.86]}
          rotation={[-0.28, -0.42, -0.12]}
          scale={1}
        />
        <mesh
          name="Cylinder 3"
          geometry={nodes['Cylinder 3'].geometry}
          material={materials.Gradient}
          castShadow
          receiveShadow
          position={[50.68, 146.31, 132.74]}
          rotation={[-1.19, -0.63, -3]}
          scale={1}
        />
        <mesh
          name="Cylinder 2"
          geometry={nodes['Cylinder 2'].geometry}
          material={materials.Gradient}
          castShadow
          receiveShadow
          position={[33.6, 200.37, 167.11]}
          rotation={[-1.19, -0.63, -3]}
          scale={1}
        />
        <mesh
          name="Cylinder"
          geometry={nodes.Cylinder.geometry}
          material={materials.Gradient}
          castShadow
          receiveShadow
          position={[-29.39, 122.1, 67.34]}
          rotation={[-1.19, -0.63, -3]}
          scale={1}
        />
        <mesh
          name="Helix 3"
          geometry={nodes['Helix 3'].geometry}
          material={materials['Gradient 3']}
          castShadow
          receiveShadow
          position={[20.1, 13.07, 81.4]}
          rotation={[2.8, -0.46, -2.96]}
          scale={1}
        />
        <mesh
          name="Helix 2"
          geometry={nodes['Helix 2'].geometry}
          material={materials.Gradient}
          castShadow
          receiveShadow
          position={[-9.32, 49.46, 64.9]}
          rotation={[-1.88, -0.74, 1.22]}
          scale={1}
        />
        <mesh
          name="Helix"
          geometry={nodes.Helix.geometry}
          material={materials['Gradient 2']}
          castShadow
          receiveShadow
          position={[-24.92, 70.64, 63.61]}
          rotation={[0.93, -0.74, 0.14]}
        />
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.72}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-674.016}
          shadow-camera-right={674.016}
          shadow-camera-top={674.016}
          shadow-camera-bottom={-674.016}
          position={[200, 300, 300]}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.45} color="#eaeaea" />
      </group>
    </>
  )
}
